[package]
name = "pitusya"
authors = ["Jujumba"]
repository = "https://github.com/Jujumba/pitusya"
description = "The Pitusya programming language"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
llvm-sys = "160.1.2"
regex = "1.8.3"