[package]
name = "pitusya"
authors = ["Jujumba"]
repository = "https://github.com/Jujumba/pitusya"
description = "The Pitusya programming language"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
libc = "0.2.146"
regex = "1.8.3"

[build-dependencies]
cc = "1.0.79"