[package]
name = "pitusya"
authors = ["Jujumba"]
repository = "https://github.com/Jujumba/pitusya"
description = "The Pitusya Programming Language"
version = "1.0.1"
edition = "2021"
license = "MIT"

[lib]
path = "src/rust/lib.rs"

[[bin]]
name = "pitusya"
path = "src/rust/main.rs"

[dependencies]
libc = "0.2.146"
regex = "1.8.3"

[build-dependencies]
cc = "1.0.79"
dotenv = "0.15.0"

[profile.release]
strip = true