reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
fn_params_layout = "Compressed"
newline_style = "Unix"
trailing_comma = "Always"
match_block_trailing_comma = true
max_width = 140