reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
fn_params_layout = "Compressed"
newline_style = "Unix"
trailing_comma = "Never"
max_width = 140
use_field_init_shorthand = true
struct_variant_width = 15