name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add nightly
      run: rustup toolchain install nightly

    - name: Build and test
      run: cargo test

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Format Check
      run: cargo +nightly fmt -- --check