name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install LLVM
      run: |
        wget -O llvm.sh https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16

    - name: Update Rust
      run: rustup update stable

    - name: Add nightly
      run: rustup toolchain install nightly

    - name: Add nightly fmt
      run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

    - name: Build and test
      run: cargo test

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Format Check
      run: cargo +nightly fmt -- --check